export type LaptopTypes = {
  _id: string;
  title: string;
  image: string;
  description: string;
  price: number;
  owner: string;
  place: string;
  vipplus: boolean | false;
  vip: boolean | false;
  supervip: boolean | false;
  brand: string;
  published: string;
  os: string;
  resolution: string;
  cpu: string;
  cpufrequence: string;
  ram: number;
  videocard: string;
  ssd: number;
  hdd: number;
  condition: string;
  createdAt: string;
};
