export type MobileType = {
  _id: string;
  title: string;
  image: string;
  description: string;
  price: number;
  owner: string;
  place: string;
  vipplus: boolean;
  vip: boolean;
  supervip: boolean;
  brand: string;
  model: string;
  osversion: string;
  selfcamera: number;
  simnum: number;
  simtype: string;
  published: number;
  screensize: number;
  screentype: string;
  battery: number;
  cameranum: number;
  features: string;
  os: string;
  internalmemory: number;
  maincamera: number;
  condition: string;
  createdAt: string;
};

export type LaptopType = {
  _id: string;
  title: string;
  image: string;
  description: string;
  price: number;
  owner: string;
  place: string;
  vipplus: boolean;
  vip: boolean;
  supervip: boolean;
  brand: string;
  published: string;
  os: string;
  resolution: string;
  cpu: string;
  cpufrequence: string;
  ram: number;
  videocard: string;
  ssd: number;
  hdd: number;
  condition: string;
  createdAt: string;
};
