import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import MainProvider from "./providers/SessionProvider";
import { Toaster } from "../components/ui/toaster";
import Footer from "@components/Footer";
import Partners from "@components/Partners";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/shop-cart.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <MainProvider>
            {children}

            <Toaster />
          </MainProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}

